INSERT INTO WAUser (USERNAME, EMAIL, PASSWORD, ROLES, ACTIVE) VALUES ('Mouse', 'minnie@disney.com', '321', 'USER',1);
INSERT INTO WAGROUP (GROUPNAME, OWNERID) VALUES ('The Ducks', 1);
-- INSERT INTO GOALS (GOALNAME, DEADLINE, GROUPID, COMPLETED) VALUES ('Our goal', 2020-02-02, 1, 0);

