CREATE TABLE WAUser(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  USERNAME VARCHAR(64) NOT NULL,
  EMAIL VARCHAR(64),
  PASSWORD VARCHAR(64) NOT NULL,
  ROLES VARCHAR(64),
  ACTIVE BIGINT NOT NULL
);

CREATE TABLE WAGROUP (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    GROUPNAME VARCHAR(64) NOT NULL,
    OWNERID BIGINT NOT NULL
);

ALTER TABLE WAGROUP ADD FOREIGN KEY (OWNERID) REFERENCES WAUser(ID);

